# Generated by Django 5.1.1 on 2024-11-30 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Equipo Desconocido', max_length=100)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], max_length=50)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('solucion', models.TextField()),
                ('promedio_calificacion', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usuario',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_usuario', to='login.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='equipo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='login.equipo'),
        ),
        migrations.CreateModel(
            name='HistorialTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.userprofile')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='historial',
            field=models.ManyToManyField(through='login.HistorialTecnico', to='login.userprofile'),
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='login.problemafrecuente')),
            ],
        ),
    ]
