# Generated by Django 5.1.1 on 2024-11-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_ticket_equipo_alter_equipo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
