# Generated by Django 5.1.1 on 2024-12-01 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_ticket_fecha_creacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacionproblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_problema', to='login.problemafrecuente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciontrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_trabajo', to='login.problemafrecuente')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_ticket', to='login.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
