# Generated by Django 5.1.1 on 2024-11-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_problema_delete_problemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('solucion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='problema',
        ),
    ]
