# Generated by Django 5.1.1 on 2024-10-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contrasena',
        ),
    ]
