# Generated by Django 5.1.1 on 2024-11-15 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_ticket_encargado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_encargado', to='login.userprofile'),
        ),
    ]
