# Generated by Django 5.1.1 on 2024-10-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_userprofile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columna_uno', models.CharField(max_length=200)),
                ('columna_dos', models.CharField(max_length=200)),
                ('columna_tres', models.CharField(max_length=200)),
                ('columna_cuatro', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tabla Test',
                'verbose_name_plural': 'Tablas Test',
                'db_table': 'tabla_test',
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id_ticket',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Asignacion',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
