# Generated by Django 5.1.1 on 2024-11-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_ticket_encargado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemafrecuente',
            old_name='descripcion',
            new_name='problema',
        ),
        migrations.AddField(
            model_name='problemafrecuente',
            name='titulo',
            field=models.CharField(default='Título por defecto', max_length=255),
            preserve_default=False,
        ),
    ]
