# Generated by Django 5.1.1 on 2024-10-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_categoria_ticket_userprofile_delete_tabla_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apellidos',
            field=models.CharField(default='Sin Apellido', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='1234', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(default='123456789', max_length=15),
        ),
    ]
