# Generated by Django 5.1.1 on 2024-11-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_rename_descripcion_problemafrecuente_problema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemafrecuente',
            name='problema',
            field=models.TextField(),
        ),
    ]
