# Generated by Django 5.1.1 on 2024-10-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_userprofile_apellidos_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('TECH', 'Problema Técnico'), ('SUP', 'Soporte General'), ('BILL', 'Problema de Facturación'), ('FEED', 'Sugerencias o Feedback'), ('OTHER', 'Otro')], max_length=50, verbose_name='Categoría'),
        ),
    ]
