# Generated by Django 5.1.1 on 2024-11-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_userprofile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemafrecuente',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
