# Generated by Django 5.1.1 on 2024-10-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_categoria_options_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
