# Generated by Django 5.1.1 on 2024-11-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_remove_equipo_categoria_remove_equipo_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
