# Generated by Django 5.1.1 on 2024-11-25 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_ticket_calificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemafrecuente',
            old_name='problema',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='problemafrecuente',
            name='calificacion',
        ),
        migrations.AddField(
            model_name='problemafrecuente',
            name='promedio_calificacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='login.problemafrecuente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
