# Generated by Django 5.1.3 on 2024-11-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_rename_problema_problemafrecuente_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
