# Generated by Django 5.1.3 on 2024-11-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_ticket_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
